import { analyzeText } from '../../../../../../src/analysis.ts'
import { getEngineProfile } from '../../../../../../src/measurement.ts'
import {
  layoutWithLines,
  prepareWithSegments,
  profilePrepare,
  setLocale,
  type PrepareOptions,
} from '../../../../../../src/layout.ts'

type Sample = {
  title: string
  text: string
  font: string
  width: number
  lineHeight: number
  options?: PrepareOptions
}

const emojiPresentationRe = /\p{Emoji_Presentation}/u
const punctuationRe = /[.,!?;:%)\]}'"”’»›…—-]/u

function parseFontSize(font: string): number {
  const match = font.match(/(\d+(?:\.\d+)?)\s*px/)
  return match ? Number.parseFloat(match[1]!) : 16
}

function isWideCharacter(ch: string): boolean {
  const code = ch.codePointAt(0)!
  return (
    (code >= 0x4E00 && code <= 0x9FFF) ||
    (code >= 0x3400 && code <= 0x4DBF) ||
    (code >= 0xF900 && code <= 0xFAFF) ||
    (code >= 0x2F800 && code <= 0x2FA1F) ||
    (code >= 0x20000 && code <= 0x2A6DF) ||
    (code >= 0x2A700 && code <= 0x2B73F) ||
    (code >= 0x2B740 && code <= 0x2B81F) ||
    (code >= 0x2B820 && code <= 0x2CEAF) ||
    (code >= 0x2CEB0 && code <= 0x2EBEF) ||
    (code >= 0x30000 && code <= 0x3134F) ||
    (code >= 0x3000 && code <= 0x303F) ||
    (code >= 0x3040 && code <= 0x309F) ||
    (code >= 0x30A0 && code <= 0x30FF) ||
    (code >= 0xAC00 && code <= 0xD7AF) ||
    (code >= 0xFF00 && code <= 0xFFEF)
  )
}

function measureWidth(text: string, font: string): number {
  const fontSize = parseFontSize(font)
  let width = 0
  for (const ch of text) {
    if (ch === ' ') width += fontSize * 0.33
    else if (ch === '\t') width += fontSize * 1.32
    else if (emojiPresentationRe.test(ch) || ch === '\uFE0F') width += fontSize
    else if (isWideCharacter(ch)) width += fontSize
    else if (punctuationRe.test(ch)) width += fontSize * 0.4
    else width += fontSize * 0.6
  }
  return width
}

class TestCanvasRenderingContext2D {
  font = ''

  measureText(text: string): { width: number } {
    return { width: measureWidth(text, this.font) }
  }
}

class TestOffscreenCanvas {
  constructor(_width: number, _height: number) {}

  getContext(_kind: string): TestCanvasRenderingContext2D {
    return new TestCanvasRenderingContext2D()
  }
}

const samples: Sample[] = [
  {
    title: 'Latin baseline',
    text: 'The quick brown fox jumps over the lazy dog.',
    font: '16px "Helvetica Neue", Helvetica, Arial, sans-serif',
    width: 120,
    lineHeight: 19,
  },
  {
    title: 'Soft hyphen continuation',
    text: 'foo trans\u00ADatlantic',
    font: '16px "Helvetica Neue", Helvetica, Arial, sans-serif',
    width: 72,
    lineHeight: 19,
  },
  {
    title: 'Arabic punctuation glue',
    text: 'فيقول:وعليك السلام',
    font: '20px "Geeza Pro", "Noto Naskh Arabic", Arial, serif',
    width: 120,
    lineHeight: 34,
  },
  {
    title: 'URL query preservation',
    text: 'see https://example.com/reports/q3?lang=ar&mode=full now',
    font: '16px "Helvetica Neue", Helvetica, Arial, sans-serif',
    width: 180,
    lineHeight: 19,
  },
  {
    title: 'CJK punctuation carry',
    text: '作者はさつき、「下人',
    font: '20px "Hiragino Mincho ProN", "Yu Mincho", serif',
    width: 100,
    lineHeight: 32,
  },
  {
    title: 'Pre-wrap tabs and hard breaks',
    text: 'foo\n\tbar baz',
    font: '16px "Helvetica Neue", Helvetica, Arial, sans-serif',
    width: 64,
    lineHeight: 19,
    options: { whiteSpace: 'pre-wrap' },
  },
]

function json(value: unknown): string {
  return JSON.stringify(value, null, 2)
}

function take<T>(xs: T[], count: number): T[] {
  return xs.slice(0, count)
}

if (typeof OffscreenCanvas === 'undefined' && typeof document === 'undefined') {
  Reflect.set(globalThis, 'OffscreenCanvas', TestOffscreenCanvas)
}

setLocale(undefined)

console.log('---')
console.log('Title: Pipeline samples')
console.log('Ticket: PRETEXT-20260328')
console.log('Status: active')
console.log('Topics:')
console.log('  - pretext')
console.log('  - text-layout')
console.log('  - browser-accuracy')
console.log('  - intern-onboarding')
console.log('DocType: reference')
console.log('Intent: long-term')
console.log('Owners: []')
console.log('RelatedFiles: []')
console.log('ExternalSources: []')
console.log('Summary: Representative pipeline snapshots generated from a ticket-local experiment script.')
console.log('LastUpdated: 2026-03-28T09:19:48.280397102-04:00')
console.log('WhatFor: Support the architecture guide with concrete examples of analysis, prepared state, and line layout.')
console.log('WhenToUse: Use when you want compact examples of Pretext intermediate representations for onboarding or debugging.')
console.log('---')
console.log()
console.log('# Pipeline Samples')
console.log()
console.log('Generated by `scripts/inspect-pipeline.ts` inside the ticket workspace.')
console.log('These are representative snapshots for explaining the analysis, measurement, and layout pipeline.')
console.log()

for (const sample of samples) {
  const profile = profilePrepare(sample.text, sample.font, sample.options)
  const analysis = analyzeText(sample.text, getEngineProfile(), sample.options?.whiteSpace)
  const prepared = prepareWithSegments(sample.text, sample.font, sample.options)
  const laidOut = layoutWithLines(prepared, sample.width, sample.lineHeight)

  console.log(`## ${sample.title}`)
  console.log()
  console.log(`- text: ${JSON.stringify(sample.text)}`)
  console.log(`- font: ${JSON.stringify(sample.font)}`)
  console.log(`- width: ${sample.width}`)
  console.log(`- lineHeight: ${sample.lineHeight}`)
  console.log(`- options: ${json(sample.options ?? { whiteSpace: 'normal' })}`)
  console.log(`- prepare profile: ${json(profile)}`)
  console.log()
  console.log('### Analysis')
  console.log()
  console.log(`- normalized: ${JSON.stringify(analysis.normalized)}`)
  console.log(`- chunks: ${json(analysis.chunks)}`)
  console.log(`- texts: ${json(analysis.texts)}`)
  console.log(`- kinds: ${json(analysis.kinds)}`)
  console.log(`- isWordLike: ${json(analysis.isWordLike)}`)
  console.log(`- starts: ${json(analysis.starts)}`)
  console.log()
  console.log('### Prepared')
  console.log()
  console.log(`- segments: ${json(prepared.segments)}`)
  console.log(`- kinds: ${json(prepared.kinds)}`)
  console.log(`- widths: ${json(take(prepared.widths, 16))}`)
  console.log(`- lineEndFitAdvances: ${json(take(prepared.lineEndFitAdvances, 16))}`)
  console.log(`- lineEndPaintAdvances: ${json(take(prepared.lineEndPaintAdvances, 16))}`)
  console.log(`- breakableWidths: ${json(take(prepared.breakableWidths, 16))}`)
  console.log(`- chunks: ${json(prepared.chunks)}`)
  console.log()
  console.log('### Layout')
  console.log()
  console.log(`- lineCount: ${laidOut.lineCount}`)
  console.log(`- height: ${laidOut.height}`)
  console.log(`- lines: ${json(laidOut.lines)}`)
  console.log()
}
